name = "TSPSA"
uuid = "205df287-5c08-41ed-8157-a90c328ff635"
authors = ["Luiz Henrique Nogueira Lorena <luiz-lorena@hotmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
